### ISSUE TITLE
Core Functionality

### ISSUE THREAD

**Issue by pumbas600** [franomai/cornercutter#3]
In order to allow for immediate testing of the modding system, the core functionality of the mod configuration system must be implemented. The selected options will then need to be stored in the frontend before being sent to the Tauri backend to activate the mod.

**Tasks:**

- [x] Test calling the Rust methods
- [x] Create general mod configuration options
- [x] Create starting skill configuration options
- [x] Create config per floor options
- [ ] Persist options -> Get configurations from Tauri backend on startup?
- [x] Create config per room options
- [x] Support config per room per floor options.
